# Site 정보
repository: your-github-username/your-repo-name

# 기본 설정
version: 2
encoding: "utf-8"
title: 김민제의 이력서
darkmode: false

# 개인 정보
name: 김민제
title: Android Developer
email: minjek90@gmail.com
website: [GitHub](https://github.com/mjkim90)

# 소셜 링크
github_username: mjkim90

# 추가 아이콘 링크 (선택)
additional_links:
  - title: LinkedIn
    icon: fab fa-linkedin
    url: https://linkedin.com/in/yourprofile

# 프로필 이미지
about_profile_image: (/images/kim-min-je.jpg "김민제 프로필")

# 소개글
about_content: |
  안녕하세요. 더 나은 앱을 만들기 위해 노력하는 안드로이드 개발자 **김민제**입니다.

  SI회사에서 커리어를 시작하여, 여행 스타트업, IoT 기반 도어락 스타트업, 핀테크 스타트업까지 다양한 환경에서 안드로이드 앱 개발을 경험하였습니다. 기능 개발뿐 아니라 유지보수, 성능 개선, 해외 단말기 대응 등도 진행하며 성장해왔습니다.

  사용자 중심의 개발을 지향하며, 더 편리하고 직관적인 서비스를 만들기 위해 항상 고민하고 도전하고 있습니다.

content:
  - title: 경력
    layout: list
    content:
      - layout: left
        title: 주식회사 이지테크핀
        sub_title: 안드로이드 앱 개발자
        caption: 2024.01 - 2025.02
        link: https://eztechfin.com
        quote: >
          핀테크 기반 블록체인 지갑 서비스 개발
        description: |
          - 블록체인 연동 지갑 앱 개발 및 유지보수
          - Web3 API, 지갑 생성/복구, 거래 서명 처리 기능 구현
          - 국내/해외 디바이스 테스트 및 대응
          - 사용자 피드백 기반 UI 개선

  - title: 학력
    layout: list
    content:
      - layout: top-right
        title: 한국IT전문학교
        sub_title: 모바일 소프트웨어 전공
        caption: 2012 - 2016
        quote: >
          안드로이드 및 모바일 앱 개발 중심의 교육 과정
        description: |
          - 안드로이드, Java, Kotlin 중심의 모바일 개발 수료
          - 졸업 프로젝트로 위치기반 여행앱 제작

  - title: 기술 스택
    layout: text
    content: |
      - **언어**: Kotlin, Java  
      - **프레임워크**: Android SDK, Jetpack, Hilt, Coroutine, Retrofit  
      - **툴**: Android Studio, Git, Firebase, Figma  
      - **기타**: REST API, WebSocket, BLE, NFC

  - title: 관심 분야
    layout: text
    content: |
      - **사용자 경험**이 중심이 되는 앱 개발
      - **디바이스 다양성**에 대응하는 기술 적용
      - **Clean Architecture**, **모듈화**, **테스트 코드 작성**

# Footer
footer_show_references: true
references_title: 요청 시 제공 가능합니다

# 빌드 설정
remote_theme: sproogen/modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/"
